/* 
 * TestAPI
 *
 * API for performing simple arithmetic operations (ASP.NET Core 8.0)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = TestAPI.Client.Client.SwaggerDateConverter;
namespace TestAPI.Client.Model
{
    /// <summary>
    /// TestAPIModelsMathRequest
    /// </summary>
    [DataContract]
        public partial class TestAPIModelsMathRequest :  IEquatable<TestAPIModelsMathRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestAPIModelsMathRequest" /> class.
        /// </summary>
        /// <param name="operation">operation (required).</param>
        /// <param name="x">x (required).</param>
        /// <param name="y">y (required).</param>
        public TestAPIModelsMathRequest(TestAPIModelsMathRequestOperationEnum operation = default(TestAPIModelsMathRequestOperationEnum), double? x = default(double?), double? y = default(double?))
        {
            // to ensure "operation" is required (not null)
            if (operation == null)
            {
                throw new InvalidDataException("operation is a required property for TestAPIModelsMathRequest and cannot be null");
            }
            else
            {
                this.Operation = operation;
            }
            // to ensure "x" is required (not null)
            if (x == null)
            {
                throw new InvalidDataException("x is a required property for TestAPIModelsMathRequest and cannot be null");
            }
            else
            {
                this.X = x;
            }
            // to ensure "y" is required (not null)
            if (y == null)
            {
                throw new InvalidDataException("y is a required property for TestAPIModelsMathRequest and cannot be null");
            }
            else
            {
                this.Y = y;
            }
        }
        
        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [DataMember(Name="operation", EmitDefaultValue=false)]
        public TestAPIModelsMathRequestOperationEnum Operation { get; set; }

        /// <summary>
        /// Gets or Sets X
        /// </summary>
        [DataMember(Name="x", EmitDefaultValue=false)]
        public double? X { get; set; }

        /// <summary>
        /// Gets or Sets Y
        /// </summary>
        [DataMember(Name="y", EmitDefaultValue=false)]
        public double? Y { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TestAPIModelsMathRequest {\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  X: ").Append(X).Append("\n");
            sb.Append("  Y: ").Append(Y).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TestAPIModelsMathRequest);
        }

        /// <summary>
        /// Returns true if TestAPIModelsMathRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TestAPIModelsMathRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestAPIModelsMathRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Operation == input.Operation ||
                    (this.Operation != null &&
                    this.Operation.Equals(input.Operation))
                ) && 
                (
                    this.X == input.X ||
                    (this.X != null &&
                    this.X.Equals(input.X))
                ) && 
                (
                    this.Y == input.Y ||
                    (this.Y != null &&
                    this.Y.Equals(input.Y))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Operation != null)
                    hashCode = hashCode * 59 + this.Operation.GetHashCode();
                if (this.X != null)
                    hashCode = hashCode * 59 + this.X.GetHashCode();
                if (this.Y != null)
                    hashCode = hashCode * 59 + this.Y.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
